### ISSUE TITLE
Why can mutual information be negative?

### ISSUE THREAD

**Issue by huerqiang** [Mamba413/fastmit#1]
您好，感谢您开发的`fastmit`，使用起来非常方便！我想请教您一个问题，我用mi.test计算的时候，发现有时候互信息的值为负数。
![image](https://user-images.githubusercontent.com/48857018/147377296-ca582f60-afe8-4704-8ee2-123daf1d3df2.png)

在我之前的理解中，互信息为0代表着两者完全独立，为正数则代表非独立。我想请问互信息为负代表什么？

**Comment by Mamba413** [comment]
你好。互信息如果为负，你可以理解成他的真实值可能跟 0 很接近。因此，估计出来的值就在 0 左右，也就是可能出现负的值。

**Comment by huerqiang** [comment]
非常感谢您的帮助！
